CREATE TABLE solicitantes (
 id_solicitante BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tipo_documento VARCHAR(20) NOT NULL,
 numero_documento VARCHAR(30) NOT NULL,
 nombres_razon_social VARCHAR(150) NOT NULL,
 ingresos_mensuales DECIMAL(18,2) NOT NULL,
 gastos_mensuales DECIMAL(18,2) NOT NULL,
 obligaciones_financieras DECIMAL(18,2) NOT NULL,
 antiguedad_laboral_negocio INT NOT NULL,
 numero_obligaciones_activas INT NOT NULL,
 puntaje_historial_pagos INT NOT NULL,
 alertas_mora INT NOT NULL,
 moneda VARCHAR(10) NOT NULL,
 estado VARCHAR(20) NOT NULL,
 fecha_registro TIMESTAMP NOT NULL,
 CONSTRAINT uk_solicitante_documento UNIQUE(tipo_documento,numero_documento),
 CONSTRAINT ck_solicitante_ingresos CHECK(ingresos_mensuales>0),
 CONSTRAINT ck_historial_pagos CHECK(puntaje_historial_pagos BETWEEN 0 AND 100)
);

CREATE TABLE modelos_scoring (
 id_modelo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 codigo VARCHAR(30) NOT NULL UNIQUE,nombre VARCHAR(150) NOT NULL,descripcion VARCHAR(255),estado VARCHAR(20) NOT NULL,
 fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE versiones_modelo (
 id_version_modelo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,id_modelo BIGINT NOT NULL,numero_version VARCHAR(20) NOT NULL,
 fecha_inicio_vigencia DATE NOT NULL,fecha_fin_vigencia DATE,estado VARCHAR(20) NOT NULL,fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_version_modelo FOREIGN KEY(id_modelo) REFERENCES modelos_scoring(id_modelo),CONSTRAINT uk_modelo_version UNIQUE(id_modelo,numero_version)
);

CREATE TABLE factores_scoring (
 id_factor BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,id_version_modelo BIGINT NOT NULL,codigo VARCHAR(30) NOT NULL,nombre VARCHAR(150) NOT NULL,
 descripcion VARCHAR(255),peso DECIMAL(5,2) NOT NULL,estado VARCHAR(20) NOT NULL,
 CONSTRAINT fk_factor_version FOREIGN KEY(id_version_modelo) REFERENCES versiones_modelo(id_version_modelo),CONSTRAINT uk_factor_version_codigo UNIQUE(id_version_modelo,codigo),CONSTRAINT ck_factor_peso CHECK(peso BETWEEN 0 AND 100)
);

CREATE TABLE reglas_evaluacion (
 id_regla BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,id_factor BIGINT NOT NULL,codigo VARCHAR(30) NOT NULL,descripcion VARCHAR(255) NOT NULL,
 valor_minimo DECIMAL(18,4) NOT NULL,valor_maximo DECIMAL(18,4) NOT NULL,puntaje INT NOT NULL,es_excluyente BOOLEAN NOT NULL DEFAULT FALSE,
 resultado_excluyente VARCHAR(30),estado VARCHAR(20) NOT NULL,
 CONSTRAINT fk_regla_factor FOREIGN KEY(id_factor) REFERENCES factores_scoring(id_factor),CONSTRAINT uk_regla_factor_codigo UNIQUE(id_factor,codigo),
 CONSTRAINT ck_regla_rango CHECK(valor_maximo>=valor_minimo),CONSTRAINT ck_regla_puntaje CHECK(puntaje BETWEEN 0 AND 100)
);

CREATE TABLE productos_crediticios (
 id_producto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,codigo VARCHAR(30) NOT NULL UNIQUE,nombre VARCHAR(150) NOT NULL,
 monto_minimo DECIMAL(18,2) NOT NULL,monto_maximo DECIMAL(18,2) NOT NULL,plazo_minimo INT NOT NULL,plazo_maximo INT NOT NULL,
 moneda VARCHAR(10) NOT NULL,estado VARCHAR(20) NOT NULL,id_modelo_scoring BIGINT NOT NULL,
 CONSTRAINT fk_producto_modelo FOREIGN KEY(id_modelo_scoring) REFERENCES modelos_scoring(id_modelo),CONSTRAINT ck_producto_montos CHECK(monto_minimo>0 AND monto_maximo>=monto_minimo),CONSTRAINT ck_producto_plazos CHECK(plazo_minimo>0 AND plazo_maximo>=plazo_minimo)
);

CREATE TABLE solicitudes_credito (
 id_solicitud BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,id_solicitante BIGINT NOT NULL,id_producto BIGINT NOT NULL,
 monto_solicitado DECIMAL(18,2) NOT NULL,plazo_solicitado INT NOT NULL,moneda VARCHAR(10) NOT NULL,finalidad_credito VARCHAR(150) NOT NULL,
 canal_origen VARCHAR(50) NOT NULL,fecha_registro TIMESTAMP NOT NULL,identificador_externo VARCHAR(100) NOT NULL,estado VARCHAR(20) NOT NULL,
 CONSTRAINT fk_solicitud_solicitante FOREIGN KEY(id_solicitante) REFERENCES solicitantes(id_solicitante),CONSTRAINT fk_solicitud_producto FOREIGN KEY(id_producto) REFERENCES productos_crediticios(id_producto),CONSTRAINT uk_solicitud_identificador_externo UNIQUE(identificador_externo),CONSTRAINT ck_solicitud_monto CHECK(monto_solicitado>0),CONSTRAINT ck_solicitud_plazo CHECK(plazo_solicitado>0)
);

CREATE TABLE evaluaciones_crediticias (
 id_evaluacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,id_solicitud BIGINT NOT NULL,id_version_modelo BIGINT NOT NULL,
 fecha_evaluacion TIMESTAMP NOT NULL,puntaje_total INT NOT NULL,resultado VARCHAR(30) NOT NULL,estado VARCHAR(30) NOT NULL,
 CONSTRAINT fk_evaluacion_solicitud FOREIGN KEY(id_solicitud) REFERENCES solicitudes_credito(id_solicitud),CONSTRAINT fk_evaluacion_version FOREIGN KEY(id_version_modelo) REFERENCES versiones_modelo(id_version_modelo),CONSTRAINT uk_evaluacion_solicitud_version UNIQUE(id_solicitud,id_version_modelo),CONSTRAINT ck_evaluacion_puntaje CHECK(puntaje_total BETWEEN 0 AND 1000)
);

CREATE TABLE resultados_factor (
 id_resultado_factor BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,id_evaluacion BIGINT NOT NULL,id_factor BIGINT NOT NULL,codigo_factor VARCHAR(30) NOT NULL,
 valor_evaluado DECIMAL(18,4) NOT NULL,peso_aplicado DECIMAL(5,2) NOT NULL,puntaje_base INT NOT NULL,puntaje_obtenido INT NOT NULL,
 regla_aplicada VARCHAR(30) NOT NULL,observacion VARCHAR(255),regla_excluyente BOOLEAN NOT NULL,resultado_excluyente VARCHAR(30),
 CONSTRAINT fk_resultado_factor_evaluacion FOREIGN KEY(id_evaluacion) REFERENCES evaluaciones_crediticias(id_evaluacion),CONSTRAINT fk_resultado_factor_factor FOREIGN KEY(id_factor) REFERENCES factores_scoring(id_factor)
);

CREATE TABLE resultados_scoring (
 id_resultado_scoring BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,id_evaluacion BIGINT NOT NULL UNIQUE,puntaje_total INT NOT NULL,
 resultado VARCHAR(30) NOT NULL,fecha_resultado TIMESTAMP NOT NULL,
 CONSTRAINT fk_resultado_scoring_evaluacion FOREIGN KEY(id_evaluacion) REFERENCES evaluaciones_crediticias(id_evaluacion),CONSTRAINT ck_resultado_scoring_puntaje CHECK(puntaje_total BETWEEN 0 AND 1000)
);

CREATE INDEX idx_solicitud_solicitante ON solicitudes_credito(id_solicitante);

CREATE INDEX idx_evaluacion_solicitud ON evaluaciones_crediticias(id_solicitud);

CREATE INDEX idx_factor_version ON factores_scoring(id_version_modelo);

CREATE INDEX idx_regla_factor ON reglas_evaluacion(id_factor);
