#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/backend-java/docker/certs"
PASS="${DEV_CERT_PASSWORD:-changeit}"
mkdir -p "$OUT"
find "$OUT" -maxdepth 1 -type f ! -name ".gitignore" ! -name "README.md" -delete

echo "Generating development CA and TLS material in $OUT"
openssl genrsa -out "$OUT/ca.key" 4096
openssl req -x509 -new -nodes -key "$OUT/ca.key" -sha256 -days 3650 \
  -subj "/CN=MotorScoring Development CA" -out "$OUT/ca.crt"

gen_signed_cert() {
  local name=$1 cn=$2 san=$3 eku=${4:-serverAuth}
  openssl genrsa -out "$OUT/${name}.key" 2048
  openssl req -new -key "$OUT/${name}.key" -subj "/CN=${cn}" -out "$OUT/${name}.csr"
  cat > "$OUT/${name}.ext" <<EXT
subjectAltName=${san}
extendedKeyUsage=${eku}
keyUsage=digitalSignature,keyEncipherment
EXT
  openssl x509 -req -in "$OUT/${name}.csr" -CA "$OUT/ca.crt" -CAkey "$OUT/ca.key" -CAcreateserial \
    -out "$OUT/${name}.crt" -days 825 -sha256 -extfile "$OUT/${name}.ext"
}

gen_signed_cert kafka-server kafka "DNS:kafka,DNS:localhost,IP:127.0.0.1" "serverAuth,clientAuth"
gen_signed_cert api-server motor-scoring-api "DNS:motor-scoring-api,DNS:localhost,IP:127.0.0.1"
gen_signed_cert postgres-server postgres "DNS:postgres,DNS:localhost,IP:127.0.0.1"

# Kafka JKS keystore/truststore.
openssl pkcs12 -export -name kafka -in "$OUT/kafka-server.crt" -inkey "$OUT/kafka-server.key" \
  -certfile "$OUT/ca.crt" -out "$OUT/kafka-server.p12" -password "pass:$PASS"
keytool -importkeystore -noprompt \
  -srckeystore "$OUT/kafka-server.p12" -srcstoretype PKCS12 -srcstorepass "$PASS" \
  -destkeystore "$OUT/kafka.keystore.jks" -deststoretype JKS -deststorepass "$PASS"
keytool -importcert -noprompt -alias motor-scoring-ca -file "$OUT/ca.crt" \
  -keystore "$OUT/kafka.truststore.jks" -storepass "$PASS"
keytool -importcert -noprompt -alias motor-scoring-ca -file "$OUT/ca.crt" \
  -keystore "$OUT/client.truststore.jks" -storepass "$PASS"

# Spring Boot HTTPS keystore.
openssl pkcs12 -export -name motor-scoring-api -in "$OUT/api-server.crt" -inkey "$OUT/api-server.key" \
  -certfile "$OUT/ca.crt" -out "$OUT/api-keystore.p12" -password "pass:$PASS"

# IAM: claves JWT RSA y secretos locales para TOTP/verificación.
# Se regeneran con cada ejecución: son EXCLUSIVAMENTE para desarrollo.
openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:3072 -out "$OUT/iam-private.pem"
openssl rsa -pubout -in "$OUT/iam-private.pem" -out "$OUT/iam-public.pem"
openssl rand -base64 32 | tr -d '\n' > "$OUT/iam-totp-aes.key"
printf '\n' >> "$OUT/iam-totp-aes.key"
openssl rand -hex 32 > "$OUT/iam-verification-pepper.txt"

# PostgreSQL expects PEM files; the generated key is already PKCS#1/PKCS#8 compatible.
chmod 600 "$OUT"/*.key "$OUT/iam-private.pem" "$OUT/iam-verification-pepper.txt"
chmod 644 "$OUT"/*.crt "$OUT"/*.jks "$OUT"/*.p12 "$OUT/iam-public.pem"
rm -f "$OUT"/*.csr "$OUT"/*.ext "$OUT"/*.srl

cat > "$OUT/README.txt" <<TXT
Development-only certificates and IAM secrets generated by scripts/generate-dev-certs.sh.
Includes TLS, JWT RSA, TOTP AES key and verification-code pepper.
Do not reuse these private keys/secrets in production.
Default TLS/JKS password: $PASS (override with DEV_CERT_PASSWORD).
TXT

echo "TLS + IAM development material ready."
echo "Import backend-java/docker/certs/ca.crt into the browser/OS trust store for a warning-free HTTPS demo."
